services:
  projectzomboid:
    image: test
    restart: unless-stopped
    container_name: projectzomboid
    ports:
      - 16261:16261/udp
      - 16262:16262/udp
      - 27015:27015/tcp
    volumes:
      - ./projectzomboid/data:/project-zomboid
      - ./projectzomboid/config:/project-zomboid-config